; Combined assembly source for Lab9 through Lab15
; Generated by GitHub Copilot assistant

; ==== Lab9 ====
; --- Begin Lab9/23065 (1).asm ---
[org ; Question: Lab9 Task 1 - compare two memory blocks byte-by-byte.
; Solution: memcompare takes pointers to block1 and block2 plus length, loops with SI/DI/CX, and returns 0 if equal or 1 if mismatch.
[org 0x100]
jmp start

block1: db 1, 2, 3, 4, 5
block2: db 1, 2, 3, 4, 5

start:
    mov ax, block1
    push ax
    mov ax, block2
    push ax
    mov ax, 5
    push ax
    call memcompare
    
    mov ax, 0x4C00
    int 0x21

memcompare:
    push bp
    mov bp, sp
    push si
    push di
    push cx

    mov si, [bp+8]
    mov di, [bp+6]
    mov cx, [bp+4]

cmp_loop:
    mov al, [si]
    cmp al, [di]
    jne mismatch
    inc si
    inc di
    loop cmp_loop

    mov ax, 0
    jmp cmp_done

mismatch:
    mov ax, 1

cmp_done:
    pop cx
    pop di
    pop si
    pop bp
    ret 6

; --- End Lab9/23065 (1).asm ---

; --- Begin Lab9/23065 (2).asm ---
; Question: Lab9 Task 2 - use a jump to a subroutine with a saved return address.
; Solution: pushes the return label address then jumps to do_add, which adds AX and BX and returns to after_add.
[org 0x100]

start:
    mov ax, 10
    mov bx, 20

    mov cx, after_add
    push cx
    jmp do_add

after_add:
    mov ax, 0x4C00
    int 0x21

do_add:
    add ax, bx
    
    pop cx
    jmp cx

; --- End Lab9/23065 (2).asm ---

; --- Begin Lab9/23065 (3).asm ---
; Question: Lab9 Task 3 - search for a bit pattern inside a byte stream and return its position.
; Solution: bitsearch scans bits by extracting each bit sequence and compares it with the pattern.
[org 0x100]
jmp start

data:    db 10101000b
pattern: dw 101b

start:
    mov ax, data
    push ax
    mov ax, 1
    push ax
    mov ax, 101b
    push ax
    mov ax, 3
    push ax
    call bitsearch

    mov ax, 0x4C00
    int 0x21

bitsearch:
    push bp
    mov bp, sp
    push bx
    push cx
    push dx
    push si
    push di

    mov si, [bp+10]
    mov bx, [bp+8]
    mov dx, [bp+6]
    mov cx, [bp+4]

    xor ah, ah
    mov al, bl
    mov bl, 8
    mul bl
    xor bh, bh
    mov bl, cl
    sub ax, bx
    inc ax
    mov bx, ax

    xor di, di

search_loop:
    call extract_bits
    cmp ax, dx
    je found
    inc di
    dec bx
    jnz search_loop
    xor ax, ax
    jmp search_done

found:
    mov ax, di
    inc ax

search_done:
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop bp
    ret 8

extract_bits:
    push bx
    push cx
    push dx
    push si
    push di

    xor bx, bx
    mov ch, cl
    xor cl, cl

next_bit:
    cmp cl, ch
    jge eb_done

    mov ax, di
    shr ax, 3
    mov bx, si
    add bx, ax
    mov al, [bx]

    mov dx, di
    and dl, 7
    mov dh, 7
    sub dh, dl
    push cx
    mov cl, dh
    shr al, cl
    pop cx
    and al, 1

    shl bx, 1
    or bl, al

    inc di
    inc cl
    jmp next_bit

eb_done:
    mov ax, bx

    pop di
    pop si
    pop dx
    pop cx
    pop bx
    ret
; --- End Lab9/23065 (3).asm ---

; --- Begin Lab9/23065 (4).asm ---
; Question: Lab9 Task 4 - merge two sorted arrays into one sorted result array.
; Solution: merge_sorted compares words from both arrays and copies the smaller into the destination buffer.
; Task 4: Merge two sorted arrays
[org 0x100]
jmp start

arr1:   dw 1, 3, 5, 7
arr2:   dw 2, 4, 6, 8
res:    times 8 dw 0

start:
    mov ax, arr1
    push ax
    mov ax, arr2
    push ax
    mov ax, 4
    push ax
    mov ax, 4
    push ax
    mov ax, res
    push ax
    call merge_sorted
    
    mov ax, 0x4C00
    int 0x21

merge_sorted:
    push bp
    mov bp, sp
    push ax
    push bx
    push cx
    push dx
    push si
    push di

    mov si, [bp+14]
    mov di, [bp+12]
    mov cx, [bp+10]
    mov dx, [bp+8]
    mov bx, [bp+6]

merge_loop:
    cmp cx, 0
    je copy_arr2
    cmp dx, 0
    je copy_arr1

    mov ax, [si]
    cmp ax, [di]
    jle take_arr1

take_arr2:
    mov ax, [di]
    mov [bx], ax
    add di, 2
    add bx, 2
    dec dx
    jmp merge_loop

take_arr1:
    mov ax, [si]
    mov [bx], ax
    add si, 2
    add bx, 2
    dec cx
    jmp merge_loop

copy_arr1:
    cmp cx, 0
    je merge_done
    mov ax, [si]
    mov [bx], ax
    add si, 2
    add bx, 2
    dec cx
    jmp copy_arr1

copy_arr2:
    cmp dx, 0
    je merge_done
    mov ax, [di]
    mov [bx], ax
    add di, 2
    add bx, 2
    dec dx
    jmp copy_arr2

merge_done:
    pop di
    pop si
    pop dx
    pop cx
    pop bx
    pop ax
    pop bp
    ret 10

; --- End Lab9/23065 (4).asm ---

; --- Begin Lab9/23065 (5).asm ---
; Question: Lab9 Task 5 - swap two memory blocks safely using the stack as temporary storage.
; Solution: pushes one block onto the stack, copies the second block over the first, then pops back into the second block.
; Task 5: Safe memory swap using stack
[org 0x100]
jmp start

block1: db 1, 2, 3, 4, 5
block2: db 6, 7, 8, 9, 10

start:
    mov ax, block1
    push ax
    mov ax, block2
    push ax
    mov ax, 5
    push ax
    call memswap
    
    mov ax, 0x4C00
    int 0x21

memswap:
    push bp
    mov bp, sp
    push ax
    push bx
    push cx
    push si
    push di

    mov si, [bp+8]
    mov di, [bp+6]
    mov cx, [bp+4]

    push cx
    mov bx, cx

push_loop:
    mov al, [si + bx - 1]
    xor ah, ah
    push ax
    dec bx
    jnz push_loop
    pop cx

    push cx
    mov si, [bp+8]
    mov di, [bp+6]

copy_loop:
    mov al, [di]
    mov [si], al
    inc si
    inc di
    loop copy_loop
    pop cx

    mov si, [bp+8]
    mov di, [bp+6]

pop_loop:
    pop ax
    mov [di], al
    inc di
    loop pop_loop

    pop di
    pop si
    pop cx
    pop bx
    pop ax
    pop bp
    ret 6

; --- End Lab9/23065 (5).asm ---

; ==== lab10 ====
; --- Begin lab10/10q1.asm ---
; Question: Lab10 Q1 - compute the geometric series sum using repeated multiplication.
; Solution: power(base, exponent) multiplies base repeatedly, then geosum uses it to sum terms with coefficients.
[org 0x0100]
jmp start

power:
    push bp
    mov bp, sp
    push bx
    push cx

    mov bx, [bp+6]
    mov cx, [bp+4]
    mov ax, 1

    cmp cx, 0
    je pw_done

pw_loop:
    mul bx
    loop pw_loop

pw_done:
    pop cx
    pop bx
    pop bp
    push ax
    ret 4

geosum:
    push bp
    mov bp, sp
    sub sp, 4

    push bx
    push cx
    push dx

    mov cx, [bp+4]
    mov word [bp-2], 0
    mov word [bp-4], 0

gs_loop:
    cmp cx, 0
    je gs_done

    mov bx, [bp+6]
    push bx
    push word [bp-2]
    call power
    pop ax

    mov bx, [bp+8]
    mul bx
    add [bp-4], ax

    inc word [bp-2]
    dec cx
    jmp gs_loop

gs_done:
    mov ax, [bp-4]
    pop dx
    pop cx
    pop bx
    mov sp, bp
    pop bp
    push ax
    ret 6

start:
    mov ax, 2
    push ax
    mov ax, 3
    push ax
    mov ax, 4
    push ax
    call geosum
    pop ax

    mov ax, 0x4c00
    int 0x21
; --- End lab10/10q1.asm ---

; --- Begin lab10/10q2.asm ---
; Question: Lab10 Q2 - rotate an 8-bit value left N times and compare the result with the original.
; Solution: rotateleft performs the bit rotation, then rotateandcompare returns 1 if rotated value is larger.
rotateleft:
    push bp
    mov bp, sp
    push cx

    mov ax, [bp+6]
    mov cx, [bp+4]

    cmp cx, 0
    je rl_done

rl_loop:
    rol ax, 1
    loop rl_loop

rl_done:
    pop cx
    pop bp
    push ax
    ret 4

rotateandcompare:
    push bp
    mov bp, sp
    push bx

    mov bx, [bp+6]

    push word [bp+6]
    push word [bp+4]
    call rotateleft
    pop ax

    cmp ax, bx
    jbe rac_zero

    mov ax, 1
    jmp rac_done

rac_zero:
    mov ax, 0

rac_done:
    pop bx
    pop bp
    push ax
    ret 4


start:
    mov ax, 0xFF00
    push ax
    mov ax, 8
    push ax
    call rotateandcompare
    pop ax   
; --- End lab10/10q2.asm ---

; --- Begin lab10/10q3.asm ---
; Question: Lab10 Q3 - reverse each byte in a word and combine two reversed bytes into DX.
; Solution: reverse_byte flips the bit order inside one byte, and mirrorswap calls it for the low and high bytes.
[org 0x0100]
jmp start

reverse_byte:
    push bp
    mov bp, sp
    push bx
    push cx

    mov bl, [bp+4]
    mov bh, 0
    mov cx, 8

rb_loop:
    shl bh, 1
    shr bl, 1
    adc bh, 0
    loop rb_loop

    mov al, bh
    mov ah, 0

    pop cx
    pop bx
    pop bp
    push ax
    ret 2

mirrorswap:
    push bp
    mov bp, sp
    push bx
    push cx

    mov ax, [bp+6]
    mov al, ah
    push ax
    call reverse_byte
    pop ax
    mov dl, al

    mov ax, [bp+4]
    push ax
    call reverse_byte
    pop ax
    mov dh, al

    pop cx
    pop bx
    pop bp
    push dx
    ret 4

start:
    mov ax, 0xAB12
    push ax
    mov ax, 0x34CD
    push ax
    call mirrorswap
    pop ax

    mov ax, 0x4C00
    int 0x21
; --- End lab10/10q3.asm ---

; --- Begin lab10/10q4.asm ---
; Question: Lab10 Q4 - mirror the low nibble into the high nibble of a byte.
; Solution: nibblemirror extracts the low nibble, reverses its bit order, and writes it into the high nibble.
[org 0x0100]
jmp start

nibblemirror:
    push bp
    mov bp, sp
    push bx
    push cx

    mov bx, [bp+4]

    mov al, bl
    and al, 0x0F

    mov ah, 0
    mov cx, 4

nm_loop:
    shl ah, 1
    shr al, 1
    adc ah, 0
    loop nm_loop

    and bl, 0x0F
    shl ah, 4
    or bl, ah

    mov ax, bx

    pop cx
    pop bx
    pop bp
    push ax
    ret 2

start:
    mov ax, 0x0005
    push ax
    call nibblemirror
    pop ax        ; AX = 00A5

    mov ax, 0x4C00
    int 0x21
; --- End lab10/10q4.asm ---

; --- Begin lab10/10q5.asm ---
; Question: Lab10 Q5 - compute the difference between the low bytes of two words and return its absolute value.
; Solution: bytediff subtracts the low bytes, uses twoscomp for negative results, and duplicates the final byte into AH.
[org 0x0100]
jmp start

twoscomp:
    push bp
    mov bp, sp

    mov al, [bp+4]
    neg al
    mov ah, 0

    pop bp
    push ax
    ret 2

bytediff:
    push bp
    mov bp, sp
    push bx

    mov ax, [bp+6]
    mov bx, [bp+4]

    mov al, ah        ; AL = upper byte of A
    sub al, bl        ; AL = AL - lower byte of B

    jns bd_positive

    push ax           ; pass AL
    call twoscomp
    pop ax
    jmp bd_store

bd_positive:
    ; AL already correct

bd_store:
    mov ah, al        ; duplicate into both bytes

    pop bx
    pop bp
    push ax
    ret 4

start:
    mov ax, 0x5020
    push ax
    mov ax, 0x0030
    push ax
    call bytediff
    pop ax            ; AX = 2020

    mov ax, 0x4C00
    int 0x21
; --- End lab10/10q5.asm ---

; ==== LAB11 ====
; --- Begin LAB11/BSCS23065 (1).asm ---
; Question: Lab11 Task 1 - clear the screen and print several colored strings to VGA text mode.
; Solution: clearscreen writes spaces to video memory, then printstr prints each string with its attribute color.
[org 0x0100]
jmp start

line1: db 'Hello, this is me saif '
line2: db 'Assembly language by bao g '
line3: db 'We are writing '
line4: db 'Each char is two bytes on screen'
line5: db 'Attribute byte controls the color of ch'
line6: db 'VGA base address is 0xB800'

len1: dw 24
len2: dw 25
len3: dw 31
len4: dw 32
len5: dw 34
len6: dw 26

clearscreen:
    push es
    push ax
    push cx
    push di
    mov ax, 0xB800
    mov es, ax
    mov di, 0
    mov cx, 2000
clrloop:
    mov word [es:di], 0x0720
    add di, 2
    loop clrloop
    pop di
    pop cx
    pop ax
    pop es
    ret

printstr:
    push bp
    mov bp, sp
    push es
    push ax
    push cx
    push si
    push di
    mov ax, 0xB800
    mov es, ax
    mov di, [bp+10]
    mov si, [bp+6]
    mov cx, [bp+4]
    mov ah, [bp+8]
nextchar:
    mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    loop nextchar
    pop di
    pop si
    pop cx
    pop ax
    pop es
    pop bp
    ret 8

start:
    call clearscreen

    mov ax, 164
    push ax
    mov ax, 0x0B
    push ax
    mov ax, line1
    push ax
    push word [len1]
    call printstr

    mov ax, 484
    push ax
    mov ax, 0x0A
    push ax
    mov ax, line2
    push ax
    push word [len2]
    call printstr

    mov ax, 804
    push ax
    mov ax, 0x0E
    push ax
    mov ax, line3
    push ax
    push word [len3]
    call printstr

    mov ax, 1124
    push ax
    mov ax, 0x0C
    push ax
    mov ax, line4
    push ax
    push word [len4]
    call printstr

    mov ax, 1444
    push ax
    mov ax, 0x0D
    push ax
    mov ax, line5
    push ax
    push word [len5]
    call printstr

    mov ax, 1764
    push ax
    mov ax, 0x0F
    push ax
    mov ax, line6
    push ax
    push word [len6]
    call printstr

    mov ax, 0x4C00
    int 0x21
; --- End LAB11/BSCS23065 (1).asm ---

; --- Begin LAB11/BSCS23065 (2).asm ---
; Question: Lab11 Task 2 - scan screen text and change the color attribute for non-space characters.
; Solution: reads bytes from VGA memory and updates the attribute byte to yellow for visible characters.
[org 0x0100]

start:
    mov ax, 0xB800
    mov es, ax
    mov di, 0           
    mov bx, 0           

scanloop:
    mov al, [es:di]     ; read ASCII byte

    cmp al, 0x20
    je isspace
    mov bx, 0           ; reset counter
    jmp changecolor

isspace:
    inc bx
    cmp bx, 3          ; 3 continuous spaces = end of text
    je done

changecolor:
    mov byte [es:di+1], 0x0E    ; overwrite attribute byte only
    add di, 2
    jmp scanloop

done:
    mov ax, 0x4C00
    int 0x21
; --- End LAB11/BSCS23065 (2).asm ---

; --- Begin LAB11/BSCS23065 (3).asm ---
; Question: Lab11 Task 3 - count the number of spaces on the screen and print the result in hex.
; Solution: scans VGA text memory, counts spaces, converts the count to hex digits, and prints them.
[org 0x0100]

start:
    mov ax, 0xB800
    mov es, ax
    mov di, 0           
    mov cx, 2000       
    mov bx, 0          

countloop:
    mov al, [es:di]     ; read ASCII byte
    cmp al, 0x20        ; is it a space?
    jne notspace
    inc bx          
notspace:
    add di, 2
    loop countloop     

    mov di, 3840        ; bottom-left position
    mov ax, bx          ; number to convert
    mov bx, 16          ; base 16
    mov cx, 0           ; digit counter

nextdigit:
    mov dx, 0           ; clear DX before division
    div bx              ; AX=quotient, DX=remainder
    cmp dl, 9           ; is remainder <= 9?
    jle isnum
    add dl, 0x37        ; A-F
    jmp push_digit
isnum:
    add dl, 0x30        ; 0-9
push_digit:
    push dx
    inc cx
    cmp ax, 0
    jnz nextdigit

printloop:
    pop dx
    mov dh, 0x07        ; white on black attr
    mov [es:di], dx     ; print digit
    add di, 2
    loop printloop

    mov ax, 0x4C00
    int 0x21
; --- End LAB11/BSCS23065 (3).asm ---

; --- Begin LAB11/BSCS23065 (4).asm ---
; Question: Lab11 Task 4 - display two reversed text lines on the screen.
; Solution: writes the reversed strings character by character to video memory.
[org 0x0100]
jmp start

line1: db 'enil rehto na si siht'
line2: db 'enil a si siht'

len1: dw 21
len2: dw 14

start:
    mov ax, 0xB800
    mov es, ax

    mov di, 0
    mov si, line1
    mov cx, [len1]
    mov ah, 0x07
l1: mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    loop l1

    mov di, 160
    mov si, line2
    mov cx, [len2]
    mov ah, 0x07
l2: mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    loop l2

    mov ax, 0x4C00
    int 0x21
; --- End LAB11/BSCS23065 (4).asm ---

; --- Begin LAB11/BSCS23065 (5).asm ---
; Question: Lab11 Task 5 - draw a diamond shape of stars on the screen using rows and spacing.
; Solution: uses row and position counters to print top and bottom halves of the diamond with spaces and stars.
[org 0x0100]
jmp start

length: dw 5
i:      dw 0
row:    dw 0

start:
    mov ax, 0xB800
    mov es, ax
    mov word [i], 0
    mov word [row], 0

toploop:
    mov ax, [i]
    cmp ax, [length]
    je bottom

    mov ax, [row]
    mov bx, 160
    mul bx
    mov di, ax

    mov cx, [length]
    sub cx, 1
    sub cx, [i]
    mov ah, 0x07
    mov al, 0x20
topspace:
    cmp cx, 0
    je topstar
    mov [es:di], ax
    add di, 2
    dec cx
    jmp topspace

topstar:
    mov cx, [i]
    shl cx, 1
    inc cx
    mov al, '*'
topstarloop:
    cmp cx, 0
    je topdone
    mov [es:di], ax
    add di, 2
    dec cx
    jmp topstarloop

topdone:
    inc word [i]
    inc word [row]
    jmp toploop

bottom:
    mov ax, [length]
    sub ax, 2
    mov [i], ax

botloop:
    mov ax, [i]
    cmp ax, 0
    jl done

    mov ax, [row]
    mov bx, 160
    mul bx
    mov di, ax

    mov cx, [length]
    sub cx, 1
    sub cx, [i]
    mov ah, 0x07
    mov al, 0x20
botspace:
    cmp cx, 0
    je botstar
    mov [es:di], ax
    add di, 2
    dec cx
    jmp botspace

botstar:
    mov cx, [i]
    shl cx, 1
    inc cx
    mov al, '*'
botstarloop:
    cmp cx, 0
    je botdone
    mov [es:di], ax
    add di, 2
    dec cx
    jmp botstarloop

botdone:
    dec word [i]
    inc word [row]
    jmp botloop

done:
    mov ax, 0x4C00
    int 0x21
; --- End LAB11/BSCS23065 (5).asm ---

; ==== LAB12 ====
; --- Begin LAB12/BSCS23065 (1).asm ---
; Question: Lab12 Task 1 - implement a moving text ticker across the top row of the screen.
; Solution: prints a message at a shifting screen column, delays, increments the column, and wraps around.
[org 0x0100]
jmp start

message: db 'Hello World!'
msglen:  dw 12
col:     dw 0

start:
    mov ax, 0xB800
    mov es, ax

ticker:
    ; clear row 0
    mov di, 0
    mov cx, 80
    mov ah, 0x07
    mov al, 0x20
clearrow:
    mov [es:di], ax
    add di, 2
    loop clearrow

    ; calculate chars to print
    mov ax, 80
    sub ax, [col]
    mov bx, [msglen]
    cmp ax, bx
    jge usefull
    mov cx, ax
    jmp startprint
usefull:
    mov cx, bx

startprint:
    mov ax, [col]
    shl ax, 1
    mov di, ax
    mov si, message
    mov ah, 0x07

printloop:
    cmp cx, 0
    je delay
    mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    dec cx
    jmp printloop

delay:
    mov cx, 0x00FF      ; reduced delay
outer:
    mov bx, 0x00FF
inner:
    dec bx
    jnz inner
    loop outer

    inc word [col]
    mov ax, [col]
    cmp ax, 80
    jl ticker
    mov word [col], 0
    jmp ticker
; --- End LAB12/BSCS23065 (1).asm ---

; --- Begin LAB12/BSCS23065 (2).asm ---
; Question: Lab12 Task 2 - animate four asterisks moving inward and outward from the screen corners.
; Solution: updates corner positions each frame, reverses direction at bounds, and redraws the asterisks.
[org 0x0100]
jmp start

row:  dw 0      ; current row of top-left corner
col:  dw 0      ; current col of top-left corner
dir:  dw 1      ; 1=inward, 0xFFFF=-1=outward

start:
    mov ax, 0xB800
    mov es, ax

mainloop:
    ; check keypress to exit
    mov ah, 0x01
    int 0x16
    jz nodone
    mov ax, 0x4C00
    int 0x21
nodone:

    ; erase all 4 old positions
    call erase

    ; update position
    mov ax, [dir]
    cmp ax, 1
    je movein

    ; moving outward
    dec word [row]
    dec word [col]
    jmp checkbounds

movein:
    inc word [row]
    inc word [col]

checkbounds:
    ; check if reached center (12,12)
    mov ax, [row]
    cmp ax, 12
    je reverse
    ; check if reached corners (0,0)
    cmp ax, 0
    je reverse
    jmp draw

reverse:
    neg word [dir]

draw:
    call drawall

    ; delay
    mov cx, 0x00FF
outer:
    mov bx, 0x00FF
inner:
    dec bx
    jnz inner
    loop outer

    jmp mainloop

; draws asterisk at all 4 corner positions

drawall:
    push ax
    push bx
    push di

    mov ah, 0x0E        ; yellow attribute
    mov al, '*'

    ; top-left: (row, col)
    mov ax, [row]
    mov bx, 80
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov [es:di], ax

    ; top-right: (row, 24-col)
    mov ax, [row]
    mul bx
    mov di, ax
    mov ax, 24
    sub ax, [col]
    add di, ax
    shl di, 1
    mov word [es:di], 0x0E2A

    ; bottom-left: (24-row, col)
    mov ax, 24
    sub ax, [row]
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0E2A

    ; bottom-right: (24-row, 24-col)
    mov ax, 24
    sub ax, [row]
    mul bx
    mov di, ax
    mov ax, 24
    sub ax, [col]
    add di, ax
    shl di, 1
    mov word [es:di], 0x0E2A

    pop di
    pop bx
    pop ax
    ret

; erases asterisk at all 4 corner positions

erase:
    push ax
    push bx
    push di

    ; top-left
    mov ax, [row]
    mov bx, 80
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0720

    ; top-right
    mov ax, [row]
    mul bx
    mov di, ax
    mov ax, 24
    sub ax, [col]
    add di, ax
    shl di, 1
    mov word [es:di], 0x0720

    ; bottom-left
    mov ax, 24
    sub ax, [row]
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0720

    ; bottom-right
    mov ax, 24
    sub ax, [row]
    mul bx
    mov di, ax
    mov ax, 24
    sub ax, [col]
    add di, ax
    shl di, 1
    mov word [es:di], 0x0720

    pop di
    pop bx
    pop ax
    ret
; --- End LAB12/BSCS23065 (2).asm ---

; --- Begin LAB12/BSCS23065 (3).asm ---
; Question: Lab12 Task 3 - search the screen buffer for the string "line" and highlight matches.
; Solution: compares a needle string with screen characters and changes the attribute bytes when found.
[org 0x0100]
jmp start

needle:    db 'line'      ; string to search for
nlen:      dw 4           ; length of search string

start:
    mov ax, 0xB800
    mov es, ax
    mov di, 0             ; current screen position (byte offset)
    mov cx, 2000          ; total screen characters

scanloop:
    ; compare needle with screen at current position
    push cx
    push di

    mov si, needle
    mov cx, [nlen]
    mov bx, di            ; save start of match position

matchloop:
    mov al, [es:bx]       ; read ASCII from screen
    mov dl, [si]          ; read char from needle
    cmp al, dl
    jne nomatch           ; mismatch, stop comparing
    add bx, 2             ; next screen char
    add si, 1             ; next needle char
    loop matchloop

    ; full match found — highlight
    pop di                ; restore start position
    push di
    mov cx, [nlen]
    mov bx, di
highlightloop:
    mov byte [es:bx+1], 0x4E  ; red background yellow text
    add bx, 2
    loop highlightloop

nomatch:
    pop di
    pop cx
    add di, 2             ; move to next screen position
    loop scanloop

    mov ax, 0x4C00
    int 0x21
; --- End LAB12/BSCS23065 (3).asm ---

; --- Begin LAB12/BSCS23065 (4).asm ---
; Question: Lab12 Task 4 - copy a block of screen text to a buffer, clear the screen, and center it.
; Solution: saves source rows to a buffer, clears video memory, then writes the buffered block centered on screen.
[org 0x0100]
jmp start

src_top:  dw 1
src_bot:  dw 3
dst_top:  dw 0

start:
    mov ax, 0xB800
    mov es, ax

    ; height = src_bot - src_top + 1 = 3
    mov ax, [src_bot]
    sub ax, [src_top]
    inc ax
    mov bx, ax              ; BX = 3

    ; dst_top = (25 - 3) / 2 = 11
    mov ax, 25
    sub ax, bx
    shr ax, 1
    mov [dst_top], ax       ; dst_top = 11

    ; step 1 - save source into buffer
    mov ax, [src_top]
    mov cx, 160
    mul cx
    mov si, ax              ; SI = row 1 offset = 160

    mov di, buffer
    mov ax, bx
    mov cx, 80
    mul cx
    mov cx, ax              ; CX = 3*80 = 240 words

saveloop:
    mov ax, [es:si]
    mov [di], ax
    add si, 2
    add di, 2
    loop saveloop

    ; step 2 - clear screen
    mov di, 0
    mov cx, 2000
    mov ah, 0x07
    mov al, 0x20
clrloop:
    mov [es:di], ax
    add di, 2
    loop clrloop

    ; step 3 - write buffer to center (row 11)
    mov ax, [dst_top]
    mov cx, 160
    mul cx
    mov di, ax              ; DI = row 11 offset = 1760

    mov si, buffer
    mov cx, 240             ; 3 rows * 80 chars

writeloop:
    mov ax, [si]
    mov [es:di], ax
    add si, 2
    add di, 2
    loop writeloop

    mov ax, 0x4C00
    int 0x21

buffer: times 480 db 0
; --- End LAB12/BSCS23065 (4).asm ---

; --- Begin LAB12/ (4).asm ---
[org 0x0100]
jmp start

msg1: db 'This is a line'
msg2: db 'This is another line'
len1: dw 14
len2: dw 20

start:
    mov ax, 0xB800
    mov es, ax

    ; print msg1 at row 1
    mov di, 160
    mov si, msg1
    mov cx, [len1]
    mov ah, 0x07
p1: mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    loop p1

    ; print msg2 at row 3
    mov di, 480
    mov si, msg2
    mov cx, [len2]
    mov ah, 0x07
p2: mov al, [si]
    mov [es:di], ax
    add di, 2
    add si, 1
    loop p2

    mov ax, 0x4C00
    int 0x21
; --- End LAB12/ (4).asm ---

; ==== Lab13 ====
; --- Begin Lab13/23065 (1).asm ---
; Question: Lab13 Task 1 - print colored text using alternating character/color pairs.
; Solution: loads string bytes and attribute bytes from data and writes them to VGA text memory.
[org 0x0100]

jmp start

chardata: db 'H', 0x0B, 'e', 0x0C, 'l', 0x0D, 'l', 0x0E, 'o', 0x0F
          db ' ', 0x07, 'S', 0x0A, 'a', 0x0B, 'i', 0x0C, 'f', 0x0D
          db 'i', 0x0E, '!', 0x0F
charcount: dw 12

; subroutine: printcolor
; receives via stack: address of chardata, count
; [bp+4] = count
; [bp+6] = address of chardata
printcolor:
    push bp
    mov bp, sp
    push si
    push di
    push ds
    push es

    mov ax, cs
    mov ds, ax
    mov ax, [bp+6]
    mov si, ax
    mov ax, 0xB800
    mov es, ax
    xor di, di
    mov cx, [bp+4]

nextchar:
    lodsb
    mov ah, [si]
    inc si
    stosw
    loop nextchar

    pop es
    pop ds
    pop di
    pop si
    pop bp
    ret 4

start:
    mov ax, cs
    mov ds, ax

    mov ax, 0xB800
    mov es, ax
    xor di, di
    mov ax, 0x0720
    mov cx, 2000
    rep stosw

    push word chardata
    push word [charcount]
    call printcolor

    mov ax, 0x4C00
    int 0x21

; --- End Lab13/23065 (1).asm ---

; --- Begin Lab13/23065 (2).asm ---
; Question: Lab13 Task 2 - animate two bouncing asterisks moving across the screen borders.
; Solution: updates positions, reverses direction at edges, erases previous positions, and redraws them.
[org 0x0100]
jmp start

; asterisk 1
r1:     dw 0
c1:     dw 0
rd1:    dw 1        ; row dir down
cd1:    dw 1        ; col dir right

; asterisk 2
r2:     dw 0
c2:     dw 79
rd2:    dw 1        ; row dir down
cd2:    dw 0xFFFF   ; col dir left (-1)

start:
    mov ax, 0xB800
    mov es, ax

    ; clear screen
    xor di, di
    mov ax, 0x0720
    mov cx, 2000
    rep stosw

mainloop:
    ; check keypress to exit
    mov ah, 0x01
    int 0x16
    jz nodone
    mov ax, 0x4C00
    int 0x21
nodone:

    ; erase asterisk 1
    mov ax, [r1]
    mov bx, 80
    mul bx
    add ax, [c1]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0720

    ; erase asterisk 2
    mov ax, [r2]
    mov bx, 80
    mul bx
    add ax, [c2]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0720

    ; update asterisk 1 position
    mov ax, [r1]
    add ax, [rd1]
    mov [r1], ax
    mov ax, [c1]
    add ax, [cd1]
    mov [c1], ax

    ; bounce asterisk 1
    mov ax, [r1]
    cmp ax, 24
    jl chkr1top
    mov word [rd1], 0xFFFF
chkr1top:
    cmp ax, 0
    jg chkc1right
    mov word [rd1], 1
chkc1right:
    mov ax, [c1]
    cmp ax, 79
    jl chkc1left
    mov word [cd1], 0xFFFF
chkc1left:
    cmp ax, 0
    jg ast2update
    mov word [cd1], 1

    ; update asterisk 2 position
ast2update:
    mov ax, [r2]
    add ax, [rd2]
    mov [r2], ax
    mov ax, [c2]
    add ax, [cd2]
    mov [c2], ax

    ; bounce asterisk 2
    mov ax, [r2]
    cmp ax, 24
    jl chkr2top
    mov word [rd2], 0xFFFF
chkr2top:
    cmp ax, 0
    jg chkc2right
    mov word [rd2], 1
chkc2right:
    mov ax, [c2]
    cmp ax, 79
    jl chkc2left
    mov word [cd2], 0xFFFF
chkc2left:
    cmp ax, 0
    jg drawboth
    mov word [cd2], 1

drawboth:
    ; draw asterisk 1
    mov ax, [r1]
    mov bx, 80
    mul bx
    add ax, [c1]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0E2A

    ; draw asterisk 2
    mov ax, [r2]
    mov bx, 80
    mul bx
    add ax, [c2]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0C2A

    ; delay
    mov cx, 0x00FF
outer:
    mov bx, 0x00FF
inner:
    dec bx
    jnz inner
    loop outer

    jmp mainloop
; --- End Lab13/23065 (2).asm ---

; --- Begin Lab13/23065 (3).asm ---
; Question: Lab13 Task 3 - count vowels in a string and display the count in hexadecimal.
; Solution: scans the string for vowel characters, increments a counter, converts the count to hex, and prints it.
[org 0x0100]
jmp start

mystring: db 'Hello saifi This Is Assembly'
strlen:   dw 36
vowelcount: dw 0

start:
    mov ax, cs
    mov ds, ax

    mov ax, 0xB800
    mov es, ax

    ; clear screen
    xor di, di
    mov ax, 0x0720
    mov cx, 2000
    rep stosw

    ; count vowels
    mov si, mystring
    mov cx, [strlen]
    mov word [vowelcount], 0

nextchar:
    lodsb               ; AL = next char, SI++
    cmp al, 'a'
    je isvowel
    cmp al, 'e'
    je isvowel
    cmp al, 'i'
    je isvowel
    cmp al, 'o'
    je isvowel
    cmp al, 'u'
    je isvowel
    cmp al, 'A'
    je isvowel
    cmp al, 'E'
    je isvowel
    cmp al, 'I'
    je isvowel
    cmp al, 'O'
    je isvowel
    cmp al, 'U'
    je isvowel
    jmp notvowel

isvowel:
    inc word [vowelcount]

notvowel:
    loop nextchar

    ; print vowel count in hex at last row (offset 3840)
    mov di, 3840
    mov ax, [vowelcount]
    mov bx, 16
    mov cx, 0

hexloop:
    mov dx, 0
    div bx
    cmp dl, 9
    jle isnum
    add dl, 0x37
    jmp pushdigit
isnum:
    add dl, 0x30
pushdigit:
    push dx
    inc cx
    cmp ax, 0
    jnz hexloop

printloop:
    pop dx
    mov dh, 0x0E
    mov [es:di], dx
    add di, 2
    loop printloop

    mov ax, 0x4C00
    int 0x21
; --- End Lab13/23065 (3).asm ---

; --- Begin Lab13/23065 (4).asm ---
; Question: Lab13 Task 4 - draw a moving asterisk around the screen perimeter in a square path.
; Solution: uses phase state to move right, down, left, and up, drawing the asterisk step by step.
[org 0x0100]
jmp start

row:    dw 0
col:    dw 0
phase:  dw 0        ; 0=top 1=right 2=bottom 3=left

start:
    mov ax, 0xB800
    mov es, ax

    xor di, di
    mov ax, 0x0720
    mov cx, 2000
    rep stosw

mainloop:
    ; check keypress
    mov ah, 0x01
    int 0x16
    jz nokey
    mov ax, 0x4C00
    int 0x21
nokey:

    ; erase old position
    mov ax, [row]
    mov bx, 80
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0720

    ; update position based on phase
    mov ax, [phase]
    cmp ax, 0
    je dotop
    cmp ax, 1
    je doright
    cmp ax, 2
    je dobottom
    jmp doleft

dotop:
    inc word [col]
    mov ax, [col]
    cmp ax, 79
    jl draw
    mov word [phase], 1
    jmp draw

doright:
    inc word [row]
    mov ax, [row]
    cmp ax, 24
    jl draw
    mov word [phase], 2
    jmp draw

dobottom:
    dec word [col]
    mov ax, [col]
    cmp ax, 0
    jg draw
    mov word [phase], 3
    jmp draw

doleft:
    dec word [row]
    mov ax, [row]
    cmp ax, 0
    jg draw
    mov word [phase], 0
    jmp draw

draw:
    ; draw asterisk at new position
    mov ax, [row]
    mov bx, 80
    mul bx
    add ax, [col]
    shl ax, 1
    mov di, ax
    mov word [es:di], 0x0B2A

    ; delay
    mov cx, 0x00FF
outer:
    mov bx, 0x00FF
inner:
    dec bx
    jnz inner
    loop outer

    jmp mainloop
; --- End Lab13/23065 (4).asm ---

; ==== Lab14 ====
; --- Begin Lab14/23065 (1).asm ---
; Question: Lab14 Task 1 - convert lowercase letters to uppercase and uppercase to lowercase while printing.
; Solution: checks ASCII ranges and adjusts letters before writing them to VGA text memory.
[org 0x100]
jmp start

message: db 'Hello World This Is COAL Lab', 0

start:
    mov ax, cs
    mov ds, ax
    mov ax, 0xb800
    mov es, ax
    xor di, di
    mov si, message
    cld

nextchar:
    lodsb
    cmp al, 0
    je done
    cmp al, 65
    jl store
    cmp al, 90
    jle toupper
    cmp al, 97
    jl store
    cmp al, 122
    jg store
    sub al, 32          ; lowercase to uppercase
    jmp store

toupper:
    add al, 32          ; uppercase to lowercase

store:
    mov ah, 0x07        ; white on black attribute
    stosw
    jmp nextchar

done:
    mov ax, 0x4c00
    int 0x21
; --- End Lab14/23065 (1).asm ---

; --- Begin Lab14/23065 (2).asm ---
; Question: Lab14 Task 2 - display a long paragraph using LODS/STOS string instructions.
; Solution: loads bytes from DS:SI and stores them with attributes to ES:DI until the terminating 0 byte.
[org 0x100]
jmp start

message: db 'This is a paragraph written in assembly language for COAL Lab at ITU Lahore. '
         db 'We are learning string instructions including LODS and STOS. '
         db 'These instructions help us process blocks of memory efficiently. '
         db 'LODS loads a byte from DS:SI into AL and increments SI automatically. '
         db 'STOS stores AX into ES:DI which points to video memory and increments DI. '
         db 'Together they allow us to read and display characters one by one. '
         db 'This paragraph is long enough to cover more than half of the DOS screen. '
         db 'Assembly language is low level but very powerful and educational. '
         db 'We are students of Information Technology University Lahore Pakistan. '
         db 'This is the end of our paragraph for Task 2 of Lab 14 COAL course.', 0

start:
    mov ax, cs
    mov ds, ax
    mov ax, 0xb800
    mov es, ax
    xor di, di          ; start from top left
    mov si, message
    cld

nextchar:
    lodsb
    cmp al, 0
    je done
    mov ah, 0x07        ; white on black attribute
    stosw
    jmp nextchar

done:
    mov ax, 0x4c00
    int 0x21
; --- End Lab14/23065 (2).asm ---

; --- Begin Lab14/23065 (3).asm ---
; Question: Lab14 Task 3 - read keyboard characters and echo them to the screen until Enter is pressed.
; Solution: waits for a key with INT 16h, then stores each character to video memory until Enter stops the loop.
[org 0x100]

start:
    mov ax, cs
    mov ds, ax
    mov ax, 0xb800
    mov es, ax
    xor di, di          ; start from top left
    cld

nextkey:
    mov ah, 0x00
    int 0x16            ; wait for keypress, ASCII in AL
    cmp al, 0x0D        ; Enter pressed?
    je done
    mov ah, 0x07        ; white on black attribute
    stosw               ; print character to screen
    jmp nextkey

done:
    mov ax, 0x4c00
    int 0x21
; --- End Lab14/23065 (3).asm ---

; --- Begin Lab14/23065 (4).asm ---
; Question: Lab14 Task 4 - detect left/right arrow press/release events and print a two-letter code.
; Solution: polls keyboard scancodes from port 60h and prints LP/LR/RP/RR for arrow press/release actions.
[org 0x100]
jmp start

lp: db 'LP'
lr: db 'LR'
rp: db 'RP'
rr: db 'RR'

start:
    mov ax, cs
    mov ds, ax
    mov ax, 0xb800
    mov es, ax
    xor di, di
    cld

poll:
    in al, 0x60         ; read scancode from keyboard port

    cmp al, 0x4B        ; left arrow press
    je printlp
    cmp al, 0xCB        ; left arrow release
    je printlr
    cmp al, 0x4D        ; right arrow press
    je printrp
    cmp al, 0xCD        ; right arrow release
    je printrr
    cmp al, 0x01        ; ESC to exit
    je done
    jmp poll

printlp:
    mov si, lp
    call printstr
    jmp poll

printlr:
    mov si, lr
    call printstr
    jmp poll

printrp:
    mov si, rp
    call printstr
    jmp poll

printrr:
    mov si, rr
    call printstr
    jmp poll

; prints 2 chars from DS:SI to ES:DI
printstr:
    lodsb
    mov ah, 0x07
    stosw
    lodsb
    mov ah, 0x07
    stosw
    ret

done:
    mov ax, 0x4c00
    int 0x21
; --- End Lab14/23065 (4).asm ---

; ==== lab15 ====
; --- Begin lab15/23065.asm ---
; Question: Lab15 Task 1 - implement a simple Tic-Tac-Toe style game with limited markers and winner detection.
; Solution: tracks player turns, board state, and uses a queue to keep only the most recent three marks for each player.
[org 0x100]
jmp start

board:      db 0,0,0,0,0,0,0,0,0    ; 0=empty 1=p1 2=p2
p1queue:    db 0xFF,0xFF,0xFF        ; LRU queue player1
p2queue:    db 0xFF,0xFF,0xFF        ; LRU queue player2
p1count:    db 0
p2count:    db 0
turn:       db 1                     ; 1=player1 2=player2
cellpos:    dw 322,330,338,642,650,658,962,970,978
row2:       db '   |   |   ',0
sep:        db '---+---+---',0
msgp1win:   db 'Player 1 Wins!', 0
msgp2win:   db 'Player 2 Wins!', 0
msgdraw:    db 'Draw!', 0
wins:       db 0,1,2, 3,4,5, 6,7,8
            db 0,3,6, 1,4,7, 2,5,8
            db 0,4,8, 2,4,6

start:
    mov ax, cs
    mov ds, ax
    mov ax, 0xb800
    mov es, ax
    cld
    call drawboard

gameloop:
    ; get keypress
    mov ah, 0x00
    int 0x16
    sub al, '0'         ; ASCII to number
    cmp al, 1
    jl gameloop
    cmp al, 9
    jg gameloop

    mov bl, al
    dec bl              ; 0-based index
    mov bh, 0

    ; check if occupied
    mov al, [board + bx]
    cmp al, 0
    jne gameloop

    ; save cell index in DL
    mov dl, bl

    mov al, [turn]
    cmp al, 1
    je p1move

p2move:
    mov al, [p2count]
    cmp al, 3
    jl p2place
    ; remove oldest p2 mark
    xor bh, bh
    mov bl, [p2queue]
    mov byte [board + bx], 0
    mov al, [p2queue+1]
    mov [p2queue], al
    mov al, [p2queue+2]
    mov [p2queue+1], al
p2place:
    xor bh, bh
    mov bl, dl
    mov byte [board + bx], 2
    mov al, [p2count]
    cmp al, 3
    jge p2qfull
    xor bh, bh
    mov bl, al
    mov [p2queue + bx], dl
    inc byte [p2count]
    jmp afterplace
p2qfull:
    mov [p2queue+2], dl
    jmp afterplace

p1move:
    mov al, [p1count]
    cmp al, 3
    jl p1place
    ; remove oldest p1 mark
    xor bh, bh
    mov bl, [p1queue]
    mov byte [board + bx], 0
    mov al, [p1queue+1]
    mov [p1queue], al
    mov al, [p1queue+2]
    mov [p1queue+1], al
p1place:
    xor bh, bh
    mov bl, dl
    mov byte [board + bx], 1
    mov al, [p1count]
    cmp al, 3
    jge p1qfull
    xor bh, bh
    mov bl, al
    mov [p1queue + bx], dl
    inc byte [p1count]
    jmp afterplace
p1qfull:
    mov [p1queue+2], dl

afterplace:
    call drawboard
    call checkwinner    ; exits if winner found

    ; check draw: all 9 cells filled
    mov cx, 9
    mov bx, 0
checkdraw:
    mov al, [board + bx]
    cmp al, 0
    je nodraw
    inc bx
    loop checkdraw
    ; draw condition
    mov di, 1280
    mov si, msgdraw
    call printrow
    mov ah, 0x00
    int 0x16
    mov ax, 0x4c00
    int 0x21
nodraw:
    ; switch turn
    mov al, [turn]
    cmp al, 1
    je tog2
    mov byte [turn], 1
    jmp gameloop
tog2:
    mov byte [turn], 2
    jmp gameloop

drawboard:
    push ax
    push cx
    push si
    push di
    call clrscr

    ; show whose turn at row 0
    mov di, 0
    mov al, [turn]
    add al, '0'         ; convert to ASCII
    mov ah, 0x0A        ; green
    stosw

    mov di, 320
    mov si, row2
    call printrow
    mov di, 480
    mov si, sep
    call printrow
    mov di, 640
    mov si, row2
    call printrow
    mov di, 800
    mov si, sep
    call printrow
    mov di, 960
    mov si, row2
    call printrow

    call drawmarks
    pop di
    pop cx
    pop si
    pop ax
    ret

printrow:
    lodsb
    cmp al, 0
    je printrowdone
    mov ah, 0x07
    stosw
    jmp printrow
printrowdone:
    ret

clrscr:
    push ax
    push cx
    push di
    xor di, di
    mov ax, 0x0720
    mov cx, 2000
    rep stosw
    pop di
    pop cx
    pop ax
    ret

drawmarks:
    push ax
    push bx
    push cx
    push si
    push di
    mov cx, 9
    mov bx, 0
nextcell:
    mov al, [board + bx]
    mov si, bx
    shl si, 1
    mov di, [cellpos + si]
    cmp al, 1
    je drawx
    cmp al, 2
    je drawo
    jmp celldone
drawx:
    mov ax, 0x0C58      ; red X
    mov [es:di], ax
    jmp celldone
drawo:
    mov ax, 0x0B4F      ; cyan O
    mov [es:di], ax
celldone:
    inc bx
    loop nextcell
    pop di
    pop si
    pop cx
    pop bx
    pop ax
    ret

checkwinner:
    push ax
    push bx
    push cx
    push si
    mov si, wins
    mov cx, 8
checkloop:
    xor bh, bh
    mov bl, [si]
    mov al, [board+bx]
    cmp al, 0
    je nextline
    mov dl, al
    mov bl, [si+1]
    mov al, [board+bx]
    cmp al, dl
    jne nextline
    mov bl, [si+2]
    mov al, [board+bx]
    cmp al, dl
    jne nextline
    ; winner found in DL
    call drawboard
    mov di, 1280
    cmp dl, 1
    je winp1
    mov si, msgp2win
    jmp printwin
winp1:
    mov si, msgp1win
printwin:
    lodsb
    cmp al, 0
    je winndone
    mov ah, 0x0E
    stosw
    jmp printwin
winndone:
    mov ah, 0x00
    int 0x16
    mov ax, 0x4c00
    int 0x21
nextline:
    add si, 3
    loop checkloop
    pop si
    pop cx
    pop bx
    pop ax
    ret